version: "3.8"

services:
  device-manager-service:
    image: $DOCKERHUB_USERNAME/iot-control-center:device-manager-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_IP: ${MONGO_DB_IP}
