apiVersion: v1
kind: Secret
metadata:
  name: iot-secrets
type: Opaque
stringData:
  MONGO_DB_USERNAME: $MONGO_DB_USERNAME
  MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
  MONGO_DB_IP: $MONGO_DB_IP
  DOCKER_HUB_USERNAME: $DOCKERHUB_USERNAME
