apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-manager-service
spec:
  selector:
    matchLabels:
      svc: device-manager-service
  replicas: 1
  template:
    metadata:
      labels:
        svc: device-manager-service
    spec:
      containers:
        - name: device-manager-container
          image: canadrian72/iot-control-center:device-manager-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
          - name: MONGO_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: iot-secrets
                key: MONGO_DB_USERNAME
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iot-secrets
                key: MONGO_DB_PASSWORD
          - name: MONGO_DB_IP
            valueFrom:
              secretKeyRef:
                name: iot-secrets
                key: MONGO_DB_IP
