apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasa-bulb-controller
spec:
  selector:
    matchLabels:
      svc: kasa-bulb-controller
  replicas: 1
  template:
    metadata:
      labels:
        svc: kasa-bulb-controller
    spec:
      containers:
        - name: kasa-bulb-container
          image: $DOCKERHUB_USERNAME/iot-control-center:kasa-bulb-controller
          imagePullPolicy: Always
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_DB_IP
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_IP
