apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighting-service
spec:
  selector:
    matchLabels:
      svc: lighting-service
  replicas: 1
  template:
    metadata:
      labels:
        svc: lighting-service
    spec:
      hostname: service.lighting
      containers:
        - name: lighting-service-container
          image: canadrian72/iot-control-center:lighting-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_DB_IP
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_IP
