apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      svc: ui
  replicas: 1
  template:
    metadata:
      labels:
        svc: ui
    spec:
      containers:
        - name: ui-container
          image: $DOCKERHUB_USERNAME/iot-control-center:ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
